In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statistics import mode 
from matplotlib import cm as cm
from sklearn import svm
import seaborn as sns
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
pd.set_option('display.max_columns', 500)

In [2]:
df = pd.read_csv('properati_caballito_train.csv')
cols = ['Unnamed: 0', 'Unnamed: 0.1','place_name', 'precio_m2_usd', 'description', 'title', 'property_type']
df.drop(cols, axis=1, inplace=True)

In [3]:
# DF
df = df.dropna()
print(df.columns) 
print(df.shape)
df.head(5)

Index(['lat', 'lon', 'price_aprox_usd', 'surface_total_in_m2',
       'price_usd_per_m2', 'expenses', 'dummy_property_type__apartment',
       'dummy_property_type__house', 'dummy_property_type__store', 'distSubte',
       'distParque', 'dummy_pileta', 'dummy_balcon', 'dummy_patio',
       'dummy_lavadero', 'dummy_cochera', 'dummy_luminoso', 'dummy_terraza',
       'dummy_quincho', 'dummy_baulera', 'dummy_parrilla', 'dummy_premium',
       'dummy_piscina', 'dummy_ascensor', 'dummy_profesional', 'dummy_alarma',
       'dummy_amenities', 'dummy_calefaccion', 'dummy_pozo', 'dummy_gimnasio',
       'dummy_aire acondicionado', 'dummy_spa', 'dummy_jacuzzi', 'dummy_cine'],
      dtype='object')
(258, 34)


lat        lon  price_aprox_usd  surface_total_in_m2  \
11 -34.625947 -58.432822           158000                   71   
44 -34.604515 -58.461172           112000                   50   
68 -34.603684 -58.381559           310000                   77   
69 -34.615499 -58.463721           102000                   54   
70 -34.615499 -58.463721           102000                   54   

    price_usd_per_m2  expenses  dummy_property_type__apartment  \
11       2225.352113    2653.0                               1   
44       2240.000000     900.0                               1   
68       4025.974026    4000.0                               1   
69       1888.888889    1800.0                               1   
70       1888.888889    1800.0                               0   

    dummy_property_type__house  dummy_property_type__store  distSubte  \
11                           0                           0   0.247603   
44                           0                           0   1.891134   
68                           0                           0   4.554738   
69                           0                           0   1.398155   
70                           0                           0   1.398155   

    distParque  dummy_pileta  dummy_balcon  dummy_patio  dummy_lavadero  \
11    0.788630             0             0            0               1   
44    1.028738             0             0            0               0   
68    4.716400             0             0            0               0   
69    0.441211             0             0            0               0   
70    0.441211             0             0            0               0   

    dummy_cochera  dummy_luminoso  dummy_terraza  dummy_quincho  \
11              0               0              0              0   
44              0               0              0              0   
68              0               0              0              0   
69              0               0              0              0   
70              0               0              0              0   

    dummy_baulera  dummy_parrilla  dummy_premium  dummy_piscina  \
11              0               0              0              0   
44              0               1              0              0   
68              0               0              0              0   
69              0               0              0              0   
70              0               0              0              0   

    dummy_ascensor  dummy_profesional  dummy_alarma  dummy_amenities  \
11               1                  0             0                0   
44               1                  0             0                0   
68               0                  0             0                0   
69               0                  0             0                0   
70               0                  0             0                0   

    dummy_calefaccion  dummy_pozo  dummy_gimnasio  dummy_aire acondicionado  \
11                  0           0               0                         0   
44                  0           0               0                         0   
68                  0           0               0                         0   
69                  0           0               0                         0   
70                  0           0               0                         0   

    dummy_spa  dummy_jacuzzi  dummy_cine  
11          0              0           0  
44          0              0           0  
68          0              0           0  
69          0              0           0  
70          0              0           0

In [26]:
#GRAFICO DE CORRELACIÓN
#k = 33
#cols = df.corr().nlargest(k,'price_usd_per_m2')['price_usd_per_m2'].index
#cm = df[cols].corr()
#plt.figure(figsize=(20,15))
#sns.heatmap(cm, annot=True, cmap = 'OrRd');

In [6]:
X = df[['lat', 'lon', 'expenses', 'surface_total_in_m2', 'dummy_property_type__apartment',
       'dummy_property_type__house', 'dummy_property_type__store', 'distSubte',
       'distParque', 'dummy_pileta', 'dummy_balcon', 'dummy_patio',
       'dummy_lavadero', 'dummy_cochera', 'dummy_luminoso', 'dummy_terraza',
       'dummy_quincho', 'dummy_baulera', 'dummy_parrilla', 'dummy_premium',
       'dummy_piscina', 'dummy_ascensor', 'dummy_profesional', 'dummy_alarma',
       'dummy_amenities', 'dummy_calefaccion', 'dummy_pozo', 'dummy_gimnasio',
       'dummy_aire acondicionado', 'dummy_spa', 'dummy_jacuzzi', 'dummy_cine']]
y = df['price_usd_per_m2']
print(X.shape)
print(y.shape)

(258, 32)
(258,)


In [7]:
# Seleccionar modelo
from sklearn.linear_model import LinearRegression
# Elegir hiperparámetros
model = LinearRegression(fit_intercept=True)

# Split entrenamiento / testeo para CV
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(dfX, y, random_state=1)
#Ajustar el modelo a los datos
model.fit(Xtrain, ytrain)
print (model.coef_)
print (model.intercept_)

[-2.10493826e+03 -6.18545840e+03  1.25106800e-01 -4.53451091e+00
  4.38329381e+02 -2.47837306e-11 -8.35598257e-12 -3.97214016e+01
  1.68452282e+02 -4.03739566e+02 -1.30042923e+02 -2.15915668e+02
  5.74326208e+00  3.26214051e+02 -7.47475213e+01 -1.11152998e+01
 -3.34348013e+02 -2.29227310e+02 -5.03920575e+01 -5.34328137e-12
  5.30902948e+02 -1.23177398e+02  2.58095009e+01 -3.99530134e+01
  4.10261079e+02  8.84286401e+01 -2.41151397e+02  7.84928550e+01
  3.66657576e+02  2.33756154e+01 -2.73455337e+02 -3.53366441e+02]
-432472.3794025557


In [8]:
ypred = model.predict(Xtest)
from sklearn import metrics
print ('MAE:', metrics.mean_absolute_error(ytest, ypred))
print ('MSE:', metrics.mean_squared_error(ytest, ypred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(ytest, ypred)))
print ('R2:', metrics.r2_score(ytest, ypred))

MAE: 274.49781578412484
MSE: 133986.07603800687
RMSE: 366.0410851776162
R2: 0.5449922066714364


## REGULARIZAR antes de LASSO

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
se = StandardScaler()

In [11]:
df_random = dfX.sample(frac=1,random_state = 42)

In [12]:
X_st = se.fit_transform(X)

In [13]:
X_st[0:5]

array([[-1.0214413 ,  0.7141658 ,  0.09082017, -0.20229539,  0.12549116,
         0.        ,  0.        , -0.65934579,  0.16314451, -0.15430335,
        -0.35586171, -0.30532006,  1.83654059, -0.39617   , -0.45963856,
        -0.40269363, -0.15430335, -0.3695455 , -0.3695455 ,  0.        ,
        -0.25712974,  3.54668118, -0.4346724 , -0.06237829, -0.51449576,
        -0.19011728, -0.12549116, -0.12549116, -0.22086305, -0.32756089,
        -0.10846523, -0.08838835],
       [ 1.51997349, -1.42910024, -0.65505966, -0.61793301,  0.12549116,
         0.        ,  0.        ,  1.37233108,  0.46380816, -0.15430335,
        -0.35586171, -0.30532006, -0.54450199, -0.39617   , -0.45963856,
        -0.40269363, -0.15430335, -0.3695455 ,  2.70602673,  0.        ,
        -0.25712974,  3.54668118, -0.4346724 , -0.06237829, -0.51449576,
        -0.19011728, -0.12549116, -0.12549116, -0.22086305, -0.32756089,
        -0.10846523, -0.08838835],
       [ 1.61844028,  4.58957176,  0.66395202, -0.0835

In [14]:
np.std(X_st,axis=0)

array([1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## LASSO sobre DS CON expensas

In [16]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import cross_val_score
model = Lasso()
model

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [17]:
results = cross_val_score(model,X_st,y,cv=5)
print(results)
print(np.mean(results))
print(np.std(results))

[0.10555682 0.31593001 0.17046702 0.38504342 0.08872867]
0.21314518493662934
0.11746478059008673


In [18]:
model.fit(X_st,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [19]:
model.coef_

array([ -21.42001033,  -95.28521809,  289.66328869, -223.4771099 ,
         63.06208967,    0.        ,    0.        ,  -11.79022227,
        145.65901344,   -9.9114755 ,  -43.37461591,  -66.44400478,
         -3.20813855,   96.69692694,  -37.28470632,   29.71776738,
        -53.3341875 ,  -65.92034191,  -24.82071877,    0.        ,
        107.85400714,   -7.86716666,    0.        ,   -8.02018092,
        142.41600092,   -0.65013814,  -56.69815594,   34.64193924,
         67.15287123,   17.17271191,  -50.56539352,  -35.37850706])

In [20]:
X_st.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

## Selección del mejor alpha

In [21]:
model_lassoCV = linear_model.LassoCV()
results = cross_val_score(model_lassoCV,X_st,y,cv=5,scoring='r2')

In [22]:
np.mean(results)

0.22665684426742733

In [23]:
np.std(results)

0.13327122591182358

In [24]:
model_lassoCV.fit(X_st,y)

LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
    max_iter=1000, n_alphas=100, n_jobs=1, normalize=False, positive=False,
    precompute='auto', random_state=None, selection='cyclic', tol=0.0001,
    verbose=False)

In [25]:
model_lassoCV.alpha_

17.708394033014173