In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statistics import mode 
from matplotlib import cm as cm
from sklearn import svm
import seaborn as sns
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
pd.set_option('display.max_columns', 500)

In [14]:
df = pd.read_csv('properati_caballito_train.csv')
cols = ['Unnamed: 0', 'Unnamed: 0.1','place_name', 'precio_m2_usd', 'expenses', 'description', 'title', 'property_type']
df.drop(cols, axis=1, inplace=True)

In [25]:
# DF
df = df.dropna()
print(df.columns) 
print(df.shape)
df.head(5)

Index(['lat', 'lon', 'price_aprox_usd', 'surface_total_in_m2',
       'price_usd_per_m2', 'dummy_property_type__apartment',
       'dummy_property_type__house', 'dummy_property_type__store', 'distSubte',
       'distParque', 'dummy_pileta', 'dummy_balcon', 'dummy_patio',
       'dummy_lavadero', 'dummy_cochera', 'dummy_luminoso', 'dummy_terraza',
       'dummy_quincho', 'dummy_baulera', 'dummy_parrilla', 'dummy_premium',
       'dummy_piscina', 'dummy_ascensor', 'dummy_profesional', 'dummy_alarma',
       'dummy_amenities', 'dummy_calefaccion', 'dummy_pozo', 'dummy_gimnasio',
       'dummy_aire acondicionado', 'dummy_spa', 'dummy_jacuzzi', 'dummy_cine'],
      dtype='object')
(1410, 33)


lat        lon  price_aprox_usd  surface_total_in_m2  \
0 -34.622211 -58.439128           110000                   50   
1 -34.623894 -58.446861           170500                  100   
2 -34.620928 -58.445874           220410                   81   
3 -34.620928 -58.445874           222780                   81   
4 -34.628786 -58.427783           108000                   70   

   price_usd_per_m2  dummy_property_type__apartment  \
0       2200.000000                               1   
1       1705.000000                               1   
2       2721.111111                               1   
3       2750.370370                               1   
4       1542.857143                               1   

   dummy_property_type__house  dummy_property_type__store  distSubte  \
0                           0                           0   0.274837   
1                           0                           0   0.168539   
2                           0                           0   0.384946   
3                           0                           0   0.384946   
4                           0                           0   0.216992   

   distParque  dummy_pileta  dummy_balcon  dummy_patio  dummy_lavadero  \
0    0.257798             0             0            0               0   
1    0.471023             0             0            0               0   
2    0.137809             0             0            0               0   
3    0.137809             0             0            0               0   
4    1.185256             0             1            0               1   

   dummy_cochera  dummy_luminoso  dummy_terraza  dummy_quincho  dummy_baulera  \
0              0               0              0              0              0   
1              0               0              0              0              0   
2              0               0              0              0              1   
3              0               0              0              0              1   
4              0               1              0              0              0   

   dummy_parrilla  dummy_premium  dummy_piscina  dummy_ascensor  \
0               0              0              0               0   
1               0              0              0               0   
2               0              0              0               0   
3               0              0              0               0   
4               0              0              0               0   

   dummy_profesional  dummy_alarma  dummy_amenities  dummy_calefaccion  \
0                  0             0                0                  0   
1                  0             0                0                  0   
2                  0             0                1                  0   
3                  0             0                1                  0   
4                  0             0                0                  0   

   dummy_pozo  dummy_gimnasio  dummy_aire acondicionado  dummy_spa  \
0           0               0                         0          0   
1           0               0                         0          0   
2           0               0                         0          0   
3           0               0                         0          0   
4           0               0                         0          0   

   dummy_jacuzzi  dummy_cine  
0              0           0  
1              0           0  
2              0           0  
3              0           0  
4              0           0

In [26]:
#GRAFICO DE CORRELACIÓN
#k = 33
#cols = df.corr().nlargest(k,'price_usd_per_m2')['price_usd_per_m2'].index
#cm = df[cols].corr()
#plt.figure(figsize=(20,15))
#sns.heatmap(cm, annot=True, cmap = 'OrRd');

In [37]:
dfX = df[['lat', 'lon', 'surface_total_in_m2', 'dummy_property_type__apartment',
       'dummy_property_type__house', 'dummy_property_type__store', 'distSubte',
       'distParque', 'dummy_pileta', 'dummy_balcon', 'dummy_patio',
       'dummy_lavadero', 'dummy_cochera', 'dummy_luminoso', 'dummy_terraza',
       'dummy_quincho', 'dummy_baulera', 'dummy_parrilla', 'dummy_premium',
       'dummy_piscina', 'dummy_ascensor', 'dummy_profesional', 'dummy_alarma',
       'dummy_amenities', 'dummy_calefaccion', 'dummy_pozo', 'dummy_gimnasio',
       'dummy_aire acondicionado', 'dummy_spa', 'dummy_jacuzzi', 'dummy_cine']]
y = df['price_usd_per_m2']
print(X.shape)
print(y.shape)

(1410, 31)
(1410,)


In [39]:
# Seleccionar modelo
from sklearn.linear_model import LinearRegression
# Elegir hiperparámetros
model = LinearRegression(fit_intercept=True)

# Split entrenamiento / testeo para CV
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(dfX, y, random_state=1)
#Ajustar el modelo a los datos
model.fit(Xtrain, ytrain)
print (model.coef_)
print (model.intercept_)

[-3.29978685e+03  4.83560046e+03 -4.72653471e+00 -1.77538890e+02
  7.07237812e+02 -5.74835498e+01 -1.65044201e+02  1.32994075e+02
 -1.40251161e+02 -7.57210530e+01 -1.42501239e+02 -1.11836065e+02
  1.71644351e+02 -1.04243863e+02  8.37353104e+01 -1.81492894e+02
 -4.65316337e+01  2.02859246e+02  7.22828324e+01  3.89935027e+02
 -1.23284689e+02 -1.77044152e+02 -5.20946159e+02  1.53844423e+02
 -1.05170390e+01 -4.48060043e+02 -3.98547513e+01  2.19087025e+02
  1.50498895e+02 -2.02015720e+02  3.81424132e+01]
171315.53845291687


In [40]:
ypred = model.predict(Xtest)
from sklearn import metrics
print ('MAE:', metrics.mean_absolute_error(ytest, ypred))
print ('MSE:', metrics.mean_squared_error(ytest, ypred))
print ('RMSE:', np.sqrt(metrics.mean_squared_error(ytest, ypred)))
print ('R2:', metrics.r2_score(ytest, ypred))

MAE: 493.9791301153305
MSE: 2473712.4894185453
RMSE: 1572.8040213003478
R2: -0.057027011939028815


## REGULARIZAR antes de LASSO

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
se = StandardScaler()

In [43]:
df_random = dfX.sample(frac=1,random_state = 42)

In [44]:
X_st = se.fit_transform(dfX)

In [45]:
X_st[0:5]

array([[-0.50112572,  0.30858086, -0.44986039,  0.31868872, -0.19762779,
        -0.12877326, -0.52495536, -0.39009388, -0.17735767, -0.33986222,
        -0.34115913, -0.4810832 , -0.47772691, -0.4368963 , -0.51546984,
        -0.20525253, -0.34631843, -0.54730172, -0.059655  , -0.37026582,
        -0.26420207, -0.44835493, -0.05333807, -0.36154351, -0.23027081,
        -0.2319734 , -0.20147061, -0.30499714, -0.46084897, -0.21264684,
        -0.24034234],
       [-0.71371398, -0.2157631 ,  0.24385232,  0.31868872, -0.19762779,
        -0.12877326, -0.64012667, -0.16229202, -0.17735767, -0.33986222,
        -0.34115913, -0.4810832 , -0.47772691, -0.4368963 , -0.51546984,
        -0.20525253, -0.34631843, -0.54730172, -0.059655  , -0.37026582,
        -0.26420207, -0.44835493, -0.05333807, -0.36154351, -0.23027081,
        -0.2319734 , -0.20147061, -0.30499714, -0.46084897, -0.21264684,
        -0.24034234],
       [-0.33904623, -0.14882937, -0.01975851,  0.31868872, -0.19762779,
       

In [46]:
np.std(X_st,axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## LASSO sobre DS sin expensas

In [48]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import cross_val_score
model = Lasso()
model

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [49]:
results = cross_val_score(model,X_st,y,cv=5)
print(results)
print(np.mean(results))
print(np.std(results))

[-0.0389617  -0.02796965 -0.14152384  0.05593133 -2.80197038]
-0.5908988469311269
1.1073110110244264


In [50]:
model.fit(X_st,y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [51]:
model.coef_

array([ 8.60074457e+01, -9.27415490e+01, -2.83318300e+02,  2.57330747e-01,
        1.01357048e+02,  1.89387781e+01, -2.32025721e+02,  4.27126315e+02,
       -1.27451598e+01,  1.37772313e+01, -5.19116603e+01, -2.40791913e+01,
        6.28682918e+01, -3.12145560e+01, -1.40022803e+01, -5.70207217e+00,
       -5.98460952e+00,  6.24887890e+01,  4.85708352e+00,  1.20784120e+02,
       -2.28609744e+01, -8.34040184e+01,  9.32077707e-01,  3.08087094e+01,
        2.32760628e+01, -1.65541243e+01,  1.72979830e+01,  4.95726188e+01,
        1.96721753e+01, -4.73517045e+01, -1.18371817e+01])

In [53]:
X_st.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

## Selección del mejor alpha

In [54]:
model_lassoCV = linear_model.LassoCV()
results = cross_val_score(model_lassoCV,X_st,y,cv=5,scoring='r2')

In [55]:
np.mean(results)

0.0063229686817035

In [56]:
np.std(results)

0.07131441370909501

In [58]:
model_lassoCV.fit(X_st,y)

LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
    max_iter=1000, n_alphas=100, n_jobs=1, normalize=False, positive=False,
    precompute='auto', random_state=None, selection='cyclic', tol=0.0001,
    verbose=False)

In [59]:
model_lassoCV.alpha_

148.42677246161202